spring.application.name=employee-service

# DB Connection Properties
spring.datasource.url=jdbc:mysql://localhost:3306/employee_catalog?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=password

# The driver class name is typically auto-detected by Spring Boot
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#Common Hibernate Configurations
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
